ALTER TABLE student ALTER COLUMN birthday DATE NOT NULL;

ALTER TABLE mark ADD CONSTRAINT mark CHECK (mark > 0 AND mark <=10);

ALTER TABLE mark ALTER COLUMN student_id BIGINT NOT NULL;

ALTER TABLE mark ALTER COLUMN subject_id BIGINT NOT NULL;

ALTER TABLE subject ADD CONSTRAINT grade CHECK (grade > 0 AND grade <= 5);

ALTER TABLE paymenttype ADD CONSTRAINT unique_name UNIQUE (name);

ALTER TABLE payment ALTER COLUMN amount DECIMAL NOT NULL;

ALTER TABLE payment ALTER COLUMN payment_date DATETIME NOT NULL;
